title: Insights Results Aggregator Utils
description: Utilities used by insights-results-aggregator and other relevant services
baseurl: "/insights-results-aggregator-utils"
url: "https://redhatinsights.github.io"

heading_anchors: true
search_enabled: false

aux_links:
  "Github repository":
    - "https://github.com/RedHatInsights/insights-results-aggregator-utils"

footer_content: "Copyright &copy; 2020 Red Hat, Inc.</a>"

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-remote-theme

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
